/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Be Vietnam Pro"', 'Inter', 'Segoe UI', 'system-ui', 'sans-serif'],
        sans:    ['"Be Vietnam Pro"', 'Inter', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono:    ['"JetBrains Mono"', '"Fira Code"', 'monospace'],
      },
      colors: {
        primary:        '#ea2804',
        'primary-deep': '#c01f00',
        canvas:         '#f9f7f3',
        bone:           '#f3f0e8',
        card:           '#ffffff',
        dark:           '#202020',
        deep:           '#000000',
        ink:            '#202020',
        body:           '#3a3a3a',
        charcoal:       '#575757',
        mute:           '#646464',
        ash:            '#8d8d8d',
        stone:          '#bbbbbb',
        'on-dark':      '#fcfcfc',
        success:        '#2b9a66',
        warning:        '#F59E0B',
        error:          '#DC2626',
        info:           '#2563EB',
        neutral:        '#6B7280',
        purple:         '#7C3AED',
      },
      borderRadius: {
        none: '0px',
        xs:   '4px',
        sm:   '6px',
        md:   '10px',
        lg:   '16px',
        full: '9999px',
      },
      spacing: {
        xxs: '2px',
        xs:  '4px',
        sm:  '8px',
        md:  '12px',
        lg:  '16px',
        xl:  '24px',
        xxl: '32px',
        xxxl:'48px',
        section: '96px',
        band: '160px',
      },
      boxShadow: {
        xs:     '0 1px 2px rgba(32,32,32,0.06)',
        sm:     '0 2px 8px rgba(32,32,32,0.08)',
        md:     '0 4px 16px rgba(32,32,32,0.10)',
        lg:     '0 8px 32px rgba(32,32,32,0.12)',
        float:  '0 8px 24px rgba(32,32,32,0.08)',
        primary:'0 4px 16px rgba(234,40,4,0.30)',
      },
    },
  },
  plugins: [],
};
